#############################################################################
# Makefile for building: qAPV.app/Contents/MacOS/qAPV
# Generated by qmake (2.01a) (Qt 4.8.2) on: Do. Jän 3 12:05:39 2013
# Project:  qAPV.pro
# Template: app
# Command: /opt/local/bin/qmake -o Makefile qAPV.pro
#############################################################################

####### Compiler, tools and options

CC            = /usr/bin/llvm-gcc-4.2
CXX           = /usr/bin/llvm-g++-4.2
DEFINES       = -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.8 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.8 -Wall -W $(DEFINES)
INCPATH       = -I/opt/local/share/qt4/mkspecs/macx-g++ -I. -I. -I/opt/local/include/QtXml -I/opt/local/include/QtGui -I/opt/local/include/QtCore -I/opt/local/include -I.
LINK          = /usr/bin/llvm-g++-4.2
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.8
LIBS          = $(SUBLIBS)   -L/opt/local/lib -lQtXml -lQtGui -lQtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /opt/local/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.8

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		wmainwindow.cpp \
		cproject.cpp \
		cobject.cpp \
		cdatasource.cpp \
		qprojecttreemodel.cpp \
		qprojecttreeview.cpp \
		cfiledatasource.cpp \
		cdata.cpp \
		qadddatasourcedialog.cpp \
		cdatasourcefactory.cpp \
		qplotwindow.cpp \
		cplot.cpp moc_wmainwindow.cpp \
		moc_cproject.cpp \
		moc_qprojecttreemodel.cpp \
		moc_qadddatasourcedialog.cpp \
		moc_qplotwindow.cpp
OBJECTS       = main.o \
		wmainwindow.o \
		cproject.o \
		cobject.o \
		cdatasource.o \
		qprojecttreemodel.o \
		qprojecttreeview.o \
		cfiledatasource.o \
		cdata.o \
		qadddatasourcedialog.o \
		cdatasourcefactory.o \
		qplotwindow.o \
		cplot.o \
		moc_wmainwindow.o \
		moc_cproject.o \
		moc_qprojecttreemodel.o \
		moc_qadddatasourcedialog.o \
		moc_qplotwindow.o
DIST          = /opt/local/share/qt4/mkspecs/common/unix.conf \
		/opt/local/share/qt4/mkspecs/common/mac.conf \
		/opt/local/share/qt4/mkspecs/common/gcc-base.conf \
		/opt/local/share/qt4/mkspecs/common/gcc-base-macx.conf \
		/opt/local/share/qt4/mkspecs/common/g++-base.conf \
		/opt/local/share/qt4/mkspecs/common/g++-macx.conf \
		/opt/local/share/qt4/mkspecs/qconfig.pri \
		/opt/local/share/qt4/mkspecs/modules/qt_phonon.pri \
		/opt/local/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/opt/local/share/qt4/mkspecs/features/qt_functions.prf \
		/opt/local/share/qt4/mkspecs/features/qt_config.prf \
		/opt/local/share/qt4/mkspecs/features/exclusive_builds.prf \
		/opt/local/share/qt4/mkspecs/features/default_pre.prf \
		/opt/local/share/qt4/mkspecs/features/mac/default_pre.prf \
		/opt/local/share/qt4/mkspecs/features/release.prf \
		/opt/local/share/qt4/mkspecs/features/default_post.prf \
		/opt/local/share/qt4/mkspecs/features/mac/default_post.prf \
		/opt/local/share/qt4/mkspecs/features/mac/x86_64.prf \
		/opt/local/share/qt4/mkspecs/features/mac/objective_c.prf \
		/opt/local/share/qt4/mkspecs/features/warn_on.prf \
		/opt/local/share/qt4/mkspecs/features/qt.prf \
		/opt/local/share/qt4/mkspecs/features/unix/thread.prf \
		/opt/local/share/qt4/mkspecs/features/moc.prf \
		/opt/local/share/qt4/mkspecs/features/mac/rez.prf \
		/opt/local/share/qt4/mkspecs/features/mac/sdk.prf \
		/opt/local/share/qt4/mkspecs/features/resources.prf \
		/opt/local/share/qt4/mkspecs/features/uic.prf \
		/opt/local/share/qt4/mkspecs/features/yacc.prf \
		/opt/local/share/qt4/mkspecs/features/lex.prf \
		/opt/local/share/qt4/mkspecs/features/include_source_dir.prf \
		qAPV.pro
QMAKE_TARGET  = qAPV
DESTDIR       = 
TARGET        = qAPV.app/Contents/MacOS/qAPV

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.8 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile qAPV.app/Contents/PkgInfo qAPV.app/Contents/Resources/empty.lproj qAPV.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_wmainwindow.h ui_qadddatasourcedialog.h ui_qplotwindow.h ui_cfiledatasource_settings.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) qAPV.app/Contents/MacOS/ || $(MKDIR) qAPV.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qAPV.pro  /opt/local/share/qt4/mkspecs/macx-g++/qmake.conf /opt/local/share/qt4/mkspecs/common/unix.conf \
		/opt/local/share/qt4/mkspecs/common/mac.conf \
		/opt/local/share/qt4/mkspecs/common/gcc-base.conf \
		/opt/local/share/qt4/mkspecs/common/gcc-base-macx.conf \
		/opt/local/share/qt4/mkspecs/common/g++-base.conf \
		/opt/local/share/qt4/mkspecs/common/g++-macx.conf \
		/opt/local/share/qt4/mkspecs/qconfig.pri \
		/opt/local/share/qt4/mkspecs/modules/qt_phonon.pri \
		/opt/local/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/opt/local/share/qt4/mkspecs/features/qt_functions.prf \
		/opt/local/share/qt4/mkspecs/features/qt_config.prf \
		/opt/local/share/qt4/mkspecs/features/exclusive_builds.prf \
		/opt/local/share/qt4/mkspecs/features/default_pre.prf \
		/opt/local/share/qt4/mkspecs/features/mac/default_pre.prf \
		/opt/local/share/qt4/mkspecs/features/release.prf \
		/opt/local/share/qt4/mkspecs/features/default_post.prf \
		/opt/local/share/qt4/mkspecs/features/mac/default_post.prf \
		/opt/local/share/qt4/mkspecs/features/mac/x86_64.prf \
		/opt/local/share/qt4/mkspecs/features/mac/objective_c.prf \
		/opt/local/share/qt4/mkspecs/features/warn_on.prf \
		/opt/local/share/qt4/mkspecs/features/qt.prf \
		/opt/local/share/qt4/mkspecs/features/unix/thread.prf \
		/opt/local/share/qt4/mkspecs/features/moc.prf \
		/opt/local/share/qt4/mkspecs/features/mac/rez.prf \
		/opt/local/share/qt4/mkspecs/features/mac/sdk.prf \
		/opt/local/share/qt4/mkspecs/features/resources.prf \
		/opt/local/share/qt4/mkspecs/features/uic.prf \
		/opt/local/share/qt4/mkspecs/features/yacc.prf \
		/opt/local/share/qt4/mkspecs/features/lex.prf \
		/opt/local/share/qt4/mkspecs/features/include_source_dir.prf \
		/opt/local/lib/libQtXml.prl \
		/opt/local/lib/libQtCore.prl \
		/opt/local/lib/libQtGui.prl
	$(QMAKE) -o Makefile qAPV.pro
/opt/local/share/qt4/mkspecs/common/unix.conf:
/opt/local/share/qt4/mkspecs/common/mac.conf:
/opt/local/share/qt4/mkspecs/common/gcc-base.conf:
/opt/local/share/qt4/mkspecs/common/gcc-base-macx.conf:
/opt/local/share/qt4/mkspecs/common/g++-base.conf:
/opt/local/share/qt4/mkspecs/common/g++-macx.conf:
/opt/local/share/qt4/mkspecs/qconfig.pri:
/opt/local/share/qt4/mkspecs/modules/qt_phonon.pri:
/opt/local/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/opt/local/share/qt4/mkspecs/features/qt_functions.prf:
/opt/local/share/qt4/mkspecs/features/qt_config.prf:
/opt/local/share/qt4/mkspecs/features/exclusive_builds.prf:
/opt/local/share/qt4/mkspecs/features/default_pre.prf:
/opt/local/share/qt4/mkspecs/features/mac/default_pre.prf:
/opt/local/share/qt4/mkspecs/features/release.prf:
/opt/local/share/qt4/mkspecs/features/default_post.prf:
/opt/local/share/qt4/mkspecs/features/mac/default_post.prf:
/opt/local/share/qt4/mkspecs/features/mac/x86_64.prf:
/opt/local/share/qt4/mkspecs/features/mac/objective_c.prf:
/opt/local/share/qt4/mkspecs/features/warn_on.prf:
/opt/local/share/qt4/mkspecs/features/qt.prf:
/opt/local/share/qt4/mkspecs/features/unix/thread.prf:
/opt/local/share/qt4/mkspecs/features/moc.prf:
/opt/local/share/qt4/mkspecs/features/mac/rez.prf:
/opt/local/share/qt4/mkspecs/features/mac/sdk.prf:
/opt/local/share/qt4/mkspecs/features/resources.prf:
/opt/local/share/qt4/mkspecs/features/uic.prf:
/opt/local/share/qt4/mkspecs/features/yacc.prf:
/opt/local/share/qt4/mkspecs/features/lex.prf:
/opt/local/share/qt4/mkspecs/features/include_source_dir.prf:
/opt/local/lib/libQtXml.prl:
/opt/local/lib/libQtCore.prl:
/opt/local/lib/libQtGui.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile qAPV.pro

qAPV.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) qAPV.app/Contents || $(MKDIR) qAPV.app/Contents 
	@$(DEL_FILE) qAPV.app/Contents/PkgInfo
	@echo "APPL????" >qAPV.app/Contents/PkgInfo
qAPV.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) qAPV.app/Contents/Resources || $(MKDIR) qAPV.app/Contents/Resources 
	@touch qAPV.app/Contents/Resources/empty.lproj
	
qAPV.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) qAPV.app/Contents || $(MKDIR) qAPV.app/Contents 
	@$(DEL_FILE) qAPV.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,qAPV,g" -e "s,@TYPEINFO@,????,g" /opt/local/share/qt4/mkspecs/macx-g++/Info.plist.app >qAPV.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/qAPV1.0.0 || $(MKDIR) .tmp/qAPV1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qAPV1.0.0/ && $(COPY_FILE) --parents wmainwindow.h cproject.h cobject.h cdatasource.h qprojecttreemodel.h qprojecttreeview.h cfiledatasource.h cdata.h caudiodata.h qadddatasourcedialog.h cdatasourcefactory.h qplotwindow.h cplot.h .tmp/qAPV1.0.0/ && $(COPY_FILE) --parents main.cpp wmainwindow.cpp cproject.cpp cobject.cpp cdatasource.cpp qprojecttreemodel.cpp qprojecttreeview.cpp cfiledatasource.cpp cdata.cpp qadddatasourcedialog.cpp cdatasourcefactory.cpp qplotwindow.cpp cplot.cpp .tmp/qAPV1.0.0/ && $(COPY_FILE) --parents wmainwindow.ui qadddatasourcedialog.ui qplotwindow.ui cfiledatasource_settings.ui .tmp/qAPV1.0.0/ && (cd `dirname .tmp/qAPV1.0.0` && $(TAR) qAPV1.0.0.tar qAPV1.0.0 && $(COMPRESS) qAPV1.0.0.tar) && $(MOVE) `dirname .tmp/qAPV1.0.0`/qAPV1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qAPV1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r qAPV.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_wmainwindow.cpp moc_cproject.cpp moc_qprojecttreemodel.cpp moc_qadddatasourcedialog.cpp moc_qplotwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_wmainwindow.cpp moc_cproject.cpp moc_qprojecttreemodel.cpp moc_qadddatasourcedialog.cpp moc_qplotwindow.cpp
moc_wmainwindow.cpp: cproject.h \
		cobject.h \
		qprojecttreemodel.h \
		qprojecttreeview.h \
		wmainwindow.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ wmainwindow.h -o moc_wmainwindow.cpp

moc_cproject.cpp: cobject.h \
		cproject.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ cproject.h -o moc_cproject.cpp

moc_qprojecttreemodel.cpp: cproject.h \
		cobject.h \
		qprojecttreemodel.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ qprojecttreemodel.h -o moc_qprojecttreemodel.cpp

moc_qadddatasourcedialog.cpp: cdatasourcefactory.h \
		cdatasource.h \
		cobject.h \
		qadddatasourcedialog.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ qadddatasourcedialog.h -o moc_qadddatasourcedialog.cpp

moc_qplotwindow.cpp: cplot.h \
		cobject.h \
		qplotwindow.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ qplotwindow.h -o moc_qplotwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_wmainwindow.h ui_qadddatasourcedialog.h ui_qplotwindow.h ui_cfiledatasource_settings.h
compiler_uic_clean:
	-$(DEL_FILE) ui_wmainwindow.h ui_qadddatasourcedialog.h ui_qplotwindow.h ui_cfiledatasource_settings.h
ui_wmainwindow.h: wmainwindow.ui \
		qprojecttreeview.h
	/opt/local/bin/uic wmainwindow.ui -o ui_wmainwindow.h

ui_qadddatasourcedialog.h: qadddatasourcedialog.ui
	/opt/local/bin/uic qadddatasourcedialog.ui -o ui_qadddatasourcedialog.h

ui_qplotwindow.h: qplotwindow.ui
	/opt/local/bin/uic qplotwindow.ui -o ui_qplotwindow.h

ui_cfiledatasource_settings.h: cfiledatasource_settings.ui
	/opt/local/bin/uic cfiledatasource_settings.ui -o ui_cfiledatasource_settings.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp wmainwindow.h \
		cproject.h \
		cobject.h \
		qprojecttreemodel.h \
		qprojecttreeview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

wmainwindow.o: wmainwindow.cpp wmainwindow.h \
		cproject.h \
		cobject.h \
		qprojecttreemodel.h \
		qprojecttreeview.h \
		ui_wmainwindow.h \
		qadddatasourcedialog.h \
		cdatasourcefactory.h \
		cdatasource.h \
		qplotwindow.h \
		cplot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wmainwindow.o wmainwindow.cpp

cproject.o: cproject.cpp cproject.h \
		cobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cproject.o cproject.cpp

cobject.o: cobject.cpp cobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cobject.o cobject.cpp

cdatasource.o: cdatasource.cpp cdatasource.h \
		cobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cdatasource.o cdatasource.cpp

qprojecttreemodel.o: qprojecttreemodel.cpp qprojecttreemodel.h \
		cproject.h \
		cobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qprojecttreemodel.o qprojecttreemodel.cpp

qprojecttreeview.o: qprojecttreeview.cpp qprojecttreeview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qprojecttreeview.o qprojecttreeview.cpp

cfiledatasource.o: cfiledatasource.cpp cfiledatasource.h \
		cdatasource.h \
		cobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cfiledatasource.o cfiledatasource.cpp

cdata.o: cdata.cpp cdata.h \
		cobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cdata.o cdata.cpp

qadddatasourcedialog.o: qadddatasourcedialog.cpp qadddatasourcedialog.h \
		cdatasourcefactory.h \
		cdatasource.h \
		cobject.h \
		ui_qadddatasourcedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qadddatasourcedialog.o qadddatasourcedialog.cpp

cdatasourcefactory.o: cdatasourcefactory.cpp cdatasourcefactory.h \
		cdatasource.h \
		cobject.h \
		cfiledatasource.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cdatasourcefactory.o cdatasourcefactory.cpp

qplotwindow.o: qplotwindow.cpp qplotwindow.h \
		cplot.h \
		cobject.h \
		ui_qplotwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qplotwindow.o qplotwindow.cpp

cplot.o: cplot.cpp cplot.h \
		cobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cplot.o cplot.cpp

moc_wmainwindow.o: moc_wmainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wmainwindow.o moc_wmainwindow.cpp

moc_cproject.o: moc_cproject.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cproject.o moc_cproject.cpp

moc_qprojecttreemodel.o: moc_qprojecttreemodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qprojecttreemodel.o moc_qprojecttreemodel.cpp

moc_qadddatasourcedialog.o: moc_qadddatasourcedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qadddatasourcedialog.o moc_qadddatasourcedialog.cpp

moc_qplotwindow.o: moc_qplotwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qplotwindow.o moc_qplotwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

